import { useLayoutEffect } from "react";
import Image from "next/image";
import { MdArrowForward } from "react-icons/md";
import Link from "next/link";
const Login = () => {
  useLayoutEffect(() => {
    const configuration = {
      referenceId: process.env.NEXT_PUBLIC_REFERENCE_ID,
      success: (data) => {
        console.log("success response", data);
      },
      failure: (error) => {
        console.log("failure reason", error);
      },
    };
    if (typeof window.initVerification === "function") {
      window.initVerification(configuration);
    } else {
      const script = document.createElement("script");
      script.type = "text/javascript";
      script.src = "https://proxy.msg91.com/assets/proxy-auth/proxy-auth.js";

      const handleLoad = () => {
        if (typeof window.initVerification === "function") {
          window.initVerification(configuration);
        } else {
          console.error("initVerification function not found");
        }
      };

      script.addEventListener("load", handleLoad);

      document.body.appendChild(script);

      return () => {
        document.body.removeChild(script);
        script.removeEventListener("load", handleLoad);
      };
    }
  }, []);

  return (
    <>
      <div className="flex w-screen md:h-screen flex-col-reverse md:flex-row">
        <div className="md:w-3/5 w-full p-6 py-12 md:px-10">
        <Image
            className="hidden md:block"
            src='/assets/brand/logo.svg'
            width={158.6}
            height={40}
            alt='viasocket'
          />
          <div className="my-6 font-bold">
            Latest updates
          </div>
          <div className="signup_img my-6 w-full relative">
            <Image
              className=""
              src='https://buffer.com/cdn-cgi/image/w=1000,fit=contain,q=90,f=auto/library/content/images/size/w600/2023/10/free-images.jpg'
              width={1000}
              height={800}
              alt='viasocket'
            />
            <p className="absolute bottom-6 left-6 font-medium text-black">Trusted by 10,000+ startups and enterprises</p>
          </div>

          <div className="flex flex-col sm:flex-row md:flex-col lg:flex-row gap-5">
            <div className="w-auto">
              <Image
                src='/assets/img/feature_ico.svg'
                width={36}
                height={36}
                alt='feature_ico'
              />
              <div className="text-xl font-semibold my-3">Proactive blocklist tracking</div>
              <p>Be the first to know if your domain is added to a DNSBLs such as those offered by Spamhaus with removal requests generated by Resend.</p>
            </div>
            <div className="w-auto">
              <Image
                src='/assets/img/feature_ico.svg'
                width={36}
                height={36}
                alt='feature_ico'
              />
              <h3 className="text-xl font-semibold my-3">Proactive blocklist tracking</h3>
              <p>Be the first to know if your domain is added to a DNSBLs such as those offered by Spamhaus with removal requests generated by Resend.</p>
            </div>
          </div>
          <p className="font-medium flex items-center justify-end mt-6">Read all latest release <MdArrowForward /></p>
        </div>

        <div className="md:w-2/5 w-full bg-white py-10 px-6 md:px-10 flex flex-col gap-4">
        <Image
            className="md:hidden block"
            src='/assets/brand/logo.svg'
            width={158.6}
            height={40}
            alt='viasocket'
          />
          <div className="text-2xl font-bold">
            Login
          </div>
          <div className="text-sm ">
            Sign up with
          </div>
          <div id={process.env.NEXT_PUBLIC_REFERENCE_ID} />
          <div className="flex ">
            <span className="text-sm">Create a new Account,</span>
            <Link href='/signup' className="ms-1 text-sm text-sky-700">SignUp</Link>
          </div>
        </div>
      </div>
    </>
  );
};
export default Login;
